set shiftwidth=4
set softtabstop=4
set expandtab
set nocompatible
set history=1000
set wildmode=list:longest
set number
set list
set autoindent
set hlsearch
set ignorecase
set smartcase
set lcs=tab:+.,eol:·
set guicursor=n-v-c:block,o:hor50,i-ci:hor15,r-cr:hor30,sm:block
set scrolloff=3
set linebreak
set confirm
set shortmess+=a
set showcmd
set statusline=[%l,%v\ %P%M]\ %f\ %r%h%w\ (%{&ff})\ %{fugitive#statusline()}
set incsearch
set ls=2
set completeopt=menuone,longest,preview
syntax on
filetype plugin on

" pathogen
call pathogen#infect()
call pathogen#helptags()

" tasklist
map <leader>td <Plug>TaskList

" gundo
map <leader>u :GundoToggle<CR>

" pep8
let g:pep8_map = '<leader>8'

" hide matches on <leader>space
nnoremap <leader><space> :nohlsearch<cr>

" show a line at column 79
 if exists("&colorcolumn")
    set colorcolumn=79
endif
highlight ColorColumn ctermbg=7

" cursor positioning
set cursorline
set cursorcolumn
highlight CursorColumn ctermbg=0 cterm=NONE
highlight CursorLine ctermbg=0 cterm=NONE

" close preview window automatically when we move around
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" sudo write this
cmap W! w !sudo tee % >/dev/null

" fix pyflakes hiding python strings with default colors
highlight SpellBad ctermbg=0 ctermfg=NONE cterm=underline

" pyflakes breaks other plugins that use the quickfix window
let g:pyflakes_use_quickfix = 0
